refactor(core): PHP 8.0 support started
Guikingone/SchedulerBundle pull request #13
Opened 2021-02-04 17:26 UTC by Guikingone

2021-02-05 13:09 UTC, jmsche commented
Congrats! :)

2021-02-05 13:28 UTC, jmsche requested changes

2021-02-05 13:28 UTC, jmsche commented on CHANGELOG.md
> + * PHP 8.0 support added ()
```suggestion
 * PHP 7.2 & 7.3 support dropped (see https://github.com/Guikingone/SchedulerBundle/pull/13)
 * PHP 8.0 support added (see https://github.com/Guikingone/SchedulerBundle/pull/13)
```

2021-02-05 13:28 UTC, jmsche commented on src/Runner/CallbackTaskRunner.php
> +            return new Output($task, trim(is_string($output) ? $output : (string) $output));
```suggestion
            return new Output($task, trim((string) $output));
```
Not sure about this one

2021-02-07 15:19 UTC, jmsche approved these changes

2021-02-08 07:51 UTC, merged

2021-02-08 07:52 UTC, Guikingone commented
Thanks @jmsche for the support and the time 🙂  👍🏻