doc(transports): Improvements
Guikingone/SchedulerBundle pull request #2
Opened 2021-01-23 08:08 UTC by Guikingone

2021-01-23 08:29 UTC, jmsche reviewed
> each one can be configured as normal

"as usual"?

2021-01-23 08:29 UTC, jmsche commented on doc/transport.md
> +Think of transport like the transports used by the following components in Symfony
```suggestion
Think of transports like the transports used by the following components in Symfony:
```

2021-01-23 08:29 UTC, jmsche commented on doc/transport.md
> +This bundle defines a set of transports, each transport has its own configuration and can be override if required.
```suggestion
This bundle defines a set of transports, each transport has its own configuration and can be overridden if required. 
```

2021-01-23 08:29 UTC, jmsche commented on doc/transport.md
> +**configuration**: This transport requires at least 2 transport to be used (each one can be configured as normal).
```suggestion
**configuration**: This transport requires at least 2 transports to be used (each one can be configured as normal).
```

2021-01-23 08:29 UTC, jmsche commented on doc/transport.md
> +**configuration**: This transport requires at least 2 transport to be used (each one can be configured as normal).
```suggestion
**configuration**: This transport requires at least 2 transports to be used (each one can be configured as normal).
```

2021-01-23 08:29 UTC, jmsche commented on doc/transport.md
> +**configuration**: This transport requires at least 2 transport to be used (each one can be configured as normal).
```suggestion
**configuration**: This transport requires at least 2 transports to be used (each one can be configured as normal).
```

2021-01-23 11:30 UTC, Guikingone commented on doc/transport.md
> +Think of transport like the transports used by the following components in Symfony
Fixed

2021-01-23 11:30 UTC, Guikingone commented on doc/transport.md
> +**configuration**: This transport requires at least 2 transport to be used (each one can be configured as normal).
Fixed

2021-01-23 11:30 UTC, Guikingone commented on doc/transport.md
> +**configuration**: This transport requires at least 2 transport to be used (each one can be configured as normal).
Fixed

2021-01-23 11:31 UTC, Guikingone commented on doc/transport.md
> +**configuration**: This transport requires at least 2 transport to be used (each one can be configured as normal).
Fixed

2021-01-23 11:31 UTC, Guikingone commented on doc/transport.md
> +This bundle defines a set of transports, each transport has its own configuration and can be override if required.
Fixed

2021-01-23 11:32 UTC, Guikingone commented
> > each one can be configured as normal
> 
> "as usual"?

Nice catch, fixed 🙂

2021-01-25 07:51 UTC, jmsche requested changes

2021-01-25 07:51 UTC, jmsche commented on doc/worker.md
> +- If there's due tasks, the worker will call the registered runners to execute each task, once every task
"If there's" => "If there are" (twice)

2021-01-25 07:53 UTC, Guikingone commented on doc/worker.md
> +- If there's due tasks, the worker will call the registered runners to execute each task, once every task
Nice catch, fixed

2021-01-29 19:29 UTC, jmsche requested changes

2021-01-29 19:29 UTC, jmsche commented on doc/worker.md
> +- If there's no due tasks, the worker use the current time and determine the "wait" period until the next minute.
```suggestion
- If there are no due tasks, the worker uses the current time and determines the "wait" period until the next minute.
```

2021-01-29 19:29 UTC, jmsche commented on doc/worker.md
> +- Once launched, the worker ask the scheduler to returns due tasks
```suggestion
- Once launched, the worker asks the scheduler to return due tasks
```

2021-01-29 19:29 UTC, jmsche commented on doc/worker.md
> +- If there are due tasks, the worker will call the registered runners to execute each task, once every task
```suggestion
- If there are due tasks, the worker will call the registered runners to execute each task. Once every task
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
> +Transports are the foundations behind the storage of tasks, once tasks are defined in the configuration
```suggestion
Transports are the foundations behind the storage of tasks: once tasks are defined in the configuration
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
> +_Note: Using the transport without the scheduler can lead to edge issues as the scheduler is synchronized with it_
```suggestion
_Note: Using the transport without the scheduler can lead to edge issues as the scheduler is synchronized with it._
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
> +_Note: Container parameters cannot be passed here as the container is not involved in the transport configuration_
```suggestion
_Note: Container parameters cannot be passed here as the container is not involved in the transport configuration._
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
> +The [LongTail](../src/Transport/LongTailTransport.php) allows to use multiple transport, it's specifically designed
```suggestion
The [LongTail](../src/Transport/LongTailTransport.php) allows to use multiple transports. It's specifically designed
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
>  this approach can help when you're scheduling tasks in a [high-stress environment](https://en.wikipedia.org/wiki/Long_tail).
```suggestion
to maximize the transport usage by always trying to use the transport with the lowest amount of tasks. 
This approach can help when you're scheduling tasks in a [high-stress environment](https://en.wikipedia.org/wiki/Long_tail).
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
> +**Requirements**: The `Redis` transport requires redis >= 4.3 at least.
```suggestion
**Requirements**: The `Redis` transport requires at least redis >= 4.3.
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
> +- The `password` related
```suggestion
- The related `password`
```

2021-01-29 19:29 UTC, jmsche commented on doc/transport.md
>  This transport can configure multiple options:
```suggestion
This transport can be configured using multiple options:
```

2021-02-01 07:54 UTC, Guikingone commented
@jmsche Are we good on this one?

2021-02-01 09:01 UTC, jmsche commented
I think so :)

2021-02-01 10:19 UTC, jmsche approved these changes

2021-02-01 12:26 UTC, merged

2021-02-01 12:27 UTC, Guikingone commented
Merged, thanks @jmsche 🎉