feat(task): fluent expression WIP
Guikingone/SchedulerBundle pull request #26
Opened 2021-02-22 21:12 UTC by Guikingone

2021-02-23 17:30 UTC, jmsche requested changes

2021-02-23 17:30 UTC, jmsche commented on doc/tasks.md
> +- [Fluent Expression](#Expression)
```suggestion
- [Fluent Expressions](#fluent-expressions)
```

2021-02-23 17:30 UTC, jmsche commented on doc/tasks.md
> +This bundle support defining tasks expression via basic cron syntax:
```suggestion
This bundle supports defining tasks expression via basic cron syntax:
```

2021-02-23 17:30 UTC, jmsche commented on doc/tasks.md
> +## Expression
```suggestion
## Fluent Expressions
```

2021-02-23 17:30 UTC, jmsche commented on doc/tasks.md
> +this bundle allows you to use "fluent" expressions thanks to [strtotime](https://www.php.net/manual/fr/function.strtotime).
Maybe add an example here?

2021-02-23 17:50 UTC, Guikingone commented on doc/tasks.md
> +This bundle support defining tasks expression via basic cron syntax:
Fixed

2021-02-23 17:53 UTC, jmsche requested changes

2021-02-23 17:53 UTC, jmsche commented on doc/best_practices.md
> +- [External ressources](#Others)
```suggestion
- [External ressources](#external-resources)
```

2021-02-23 17:53 UTC, jmsche commented on doc/best_practices.md
> +When using transports that rely on network calls, you must keep in mind that this transport
```suggestion
When using transports that rely on network calls, you must keep in mind that these transports
```

2021-02-23 17:53 UTC, jmsche commented on doc/best_practices.md
> +## Others
```suggestion
## External resources
```

2021-02-24 09:46 UTC, Guikingone commented on doc/best_practices.md
> +## Others
Fixed

2021-02-24 09:46 UTC, Guikingone commented on doc/tasks.md
> +## Expression
Fixed

2021-02-24 09:47 UTC, Guikingone commented on doc/best_practices.md
> +When using transports that rely on network calls, you must keep in mind that this transport
Fixed

2021-02-24 12:25 UTC, Guikingone commented on doc/best_practices.md
> +- [External ressources](#Others)
Fixed

2021-02-24 12:26 UTC, Guikingone commented on doc/tasks.md
> +- [Fluent Expression](#Expression)
Fixed

2021-02-25 17:22 UTC, Guikingone commented on doc/tasks.md
> +this bundle allows you to use "fluent" expressions thanks to [strtotime](https://www.php.net/manual/fr/function.strtotime).
Improved

2021-02-26 07:31 UTC, merged